import { 
  EducationalModule, 
  ProgressionLevel, 
  StressTestCase, 
  CareerLadderStep, 
  MovementSignature, 
  SharedProfileData,
  UoPeopleComparisonMetric 
} from '../types/university';

export const UO_PEOPLE_COMPARISON: UoPeopleComparisonMetric[] = [
  {
    pillar: 'Course Delivery',
    uoPeopleApproach: 'Online asynchronous coursework & peer evaluation',
    felUniversityApproach: 'AI Coach (Gemini Layer + Neuro-Mechanic IP) + In-Home Facilitation',
    institutionalOutcome: 'Zero-barrier self-paced mastery combined with human relational grounding'
  },
  {
    pillar: 'Accreditation / Credentials',
    uoPeopleApproach: 'DEAC / Regional US academic accreditation',
    felUniversityApproach: 'PRQ Biomechanical Profiling, Movement Signatures, Verifiable Creator Cards',
    institutionalOutcome: 'Outcome-verified physical/cognitive portfolios accepted by scouts & partners'
  },
  {
    pillar: 'Student Community',
    uoPeopleApproach: 'Global discussion forums & study groups',
    felUniversityApproach: 'Creator Card economy, Arena leaderboards, Peer Colosseum sync',
    institutionalOutcome: 'Gamified social proof, tokenized mastery, and high-trust peer bonding'
  },
  {
    pillar: 'Faculty / Instruction',
    uoPeopleApproach: 'Volunteer online professors & peer course instructors',
    felUniversityApproach: 'Certified in-home facilitators trained on FMS1 / RNT protocols',
    institutionalOutcome: 'Scarce, high-value in-person hours focused on tactile application'
  },
  {
    pillar: 'Access & Economic Model',
    uoPeopleApproach: 'Tuition-free with modest assessment / graduation fees',
    felUniversityApproach: 'Low-friction digital app entry; paid in-home facilitator career pipeline',
    institutionalOutcome: 'Self-funding train-the-trainer ecosystem creating legitimate local jobs'
  }
];

export const INITIAL_MOVEMENT_SIGNATURE: MovementSignature = {
  scanDate: '2026-08-14',
  intervalWeek: 4,
  prqScore: 0.84,
  asymmetryIndex: 7.2,
  mobilityScore: 78,
  stabilityScore: 86,
  reactiveStiffness: 24.8,
  deepSquatScore: 2,
  hurdleStepScore: 2,
  inlineLungeScore: 3,
  aslrScore: 2,
  trunkStabilityScore: 3,
  rotaryStabilityScore: 2,
  shoulderMobilityScore: 2,
  compensationPatterns: [
    'Right ankle dorsiflexion restriction during deep descent',
    'Mild trunk forward lean compensation at peak knee flexion',
    'Right glute medius activation delay in single leg transition'
  ],
  restrictedJoints: ['Right Talocrural (Ankle)', 'Thoracic Spine T4-T8'],
  kineticChainLeakage: {
    ankle: 14.2,
    knee: 6.8,
    hip: 11.5,
    lumbar: 4.1
  },
  diagnosticNotes: 'Estimated engagement index shows strong neuromuscular firing in vertical vectors with minor posterior chain energy leakage during penultimate heel strike.',
  disclaimer: 'All outputs generated by the Neuro-Mechanic Mirror represent estimated kinematic engagement and biomechanical performance modeling. Non-clinical diagnostic framework.'
};

export const PROGRESSION_SERIES: ProgressionLevel[] = [
  {
    level: 1,
    title: 'Level 1 — Foundational Movement Competency',
    subtitle: 'Mobility, Motor Control & Basic Loading',
    description: 'Establish symmetrical joint baseline, eliminate kinetic chain energy leaks, and restore reciprocal neuromuscular inhibition before adding velocity.',
    unlocked: true,
    expressionModes: ['Diagnostic Mirror', 'Mobility Circuit', 'Wall Ankle Piston'],
    competencies: [
      {
        id: 'c1_ankle_piston',
        name: 'Ankle Piston & Subtalar Joint Stiffness',
        fmsPrerequisite: 'Deep Squat >= 2 with symmetrical tibia angle',
        criteria: 'Achieve >= 38 deg closed-chain dorsiflexion without pronation collapse.',
        completed: true,
        verificationStatus: 'verified'
      },
      {
        id: 'c1_core_bracing',
        name: 'Intra-Abdominal Pressure & Anti-Rotation Bracing',
        fmsPrerequisite: 'Rotary Stability >= 2 without lumbar hyperextension',
        criteria: 'Hold 45s asymmetric pallof press with zero pelvic tilt deviation.',
        completed: true,
        verificationStatus: 'verified'
      },
      {
        id: 'c1_posterior_hinge',
        name: 'RNT Hip Hinge & Hamstring Eccentric Tolerance',
        fmsPrerequisite: 'Active Straight Leg Raise >= 2 bilateral symmetry',
        criteria: 'Execute 5x tempo RDL maintaining neutral lumbar spine under 0.5x bodyweight.',
        completed: true,
        verificationStatus: 'verified'
      }
    ]
  },
  {
    level: 2,
    title: 'Level 2 — Sport-General Athleticism',
    subtitle: 'Rate of Force Development, Deceleration & Multi-Planar Force',
    description: 'Transition foundational motor control into high-velocity Stretch-Shortening Cycle (SSC) efficiency and multi-axis deceleration mechanics.',
    unlocked: true,
    expressionModes: ['Apex Evaluation', 'Penultimate Lab', 'Reactive Decel Ring'],
    competencies: [
      {
        id: 'c2_penultimate_stride',
        name: 'Penultimate Stride Horizontal-to-Vertical Braking',
        fmsPrerequisite: 'Hurdle Step >= 2 & In-Line Lunge >= 2',
        criteria: 'Ground Contact Time (GCT) < 190ms with > 82% kinetic energy transfer.',
        completed: true,
        verificationStatus: 'verified'
      },
      {
        id: 'c2_triple_extension',
        name: 'Triple Extension Synchronization & Plantarflexion Burst',
        fmsPrerequisite: 'Trunk Stability Push-Up >= 2',
        criteria: 'Simultaneous hip, knee, ankle peak extension within 28ms window.',
        completed: false,
        verificationStatus: 'in-progress'
      },
      {
        id: 'c2_lateral_deceleration',
        name: 'Frontal Plane Deceleration & Knee Valgus Resistance',
        fmsPrerequisite: 'Single Leg Stance symmetry > 90%',
        criteria: 'Zero knee abduction angle during 45-degree lateral cut deceleration.',
        completed: false,
        verificationStatus: 'in-progress'
      }
    ]
  },
  {
    level: 3,
    title: 'Level 3 — Sport-Specific Expression',
    subtitle: 'Dynamic Arena Context, Combat & Complex Flight Vectors',
    description: 'Apply peak neuromuscular efficiency under game stress, fatigue variables, opponent interference, and high-consequence spatial environments.',
    unlocked: false,
    expressionModes: ['Dunk Contest Engine', 'Streetball Colosseum', 'Board Sport Flight', 'Karate Dojo Combat'],
    competencies: [
      {
        id: 'c3_flight_apex',
        name: 'Dunk Apex Articulation & Rim Clearance Vector',
        fmsPrerequisite: 'All Level 1 & 2 Competencies Verified + PRQ >= 0.80',
        criteria: 'Maintain trunk control through 0.65s+ flight duration with controlled deceleration landing.',
        completed: false,
        verificationStatus: 'locked'
      },
      {
        id: 'c3_reactive_decision',
        name: 'Fatigue-State Cognitive Read & Kinetic Execution',
        fmsPrerequisite: 'Brain Brawl Cognitive Sync > 85% accuracy',
        criteria: 'Execute optimal takeoff vector choice in < 150ms under simulated defender closing speed.',
        completed: false,
        verificationStatus: 'locked'
      }
    ]
  }
];

export const BLUEPRINT_MODULES: EducationalModule[] = [
  {
    id: 'module_01_foundations',
    number: 1,
    title: 'Foundations of the Neuro-Mechanic',
    subtitle: 'Motor Learning, Stretch-Shortening Cycles (SSC) & RNT Framework',
    wordCountEstimate: '42,000 words (Curriculum Core)',
    coreConcepts: [
      'The Central Nervous System as the supreme governor of force output',
      'Reactive Neuromuscular Training (RNT): Feeding the dysfunction to trigger reflex correction',
      'Elastic recoil physics: Tendinous compliance vs muscular active stiffness',
      'Why conscious muscle contraction is too slow for elite athletic maneuvers'
    ],
    blueprintTopics: [
      'Motor Unit Recruitment Thresholds',
      'Henneman Size Principle in Elastic Takeoffs',
      'Golgi Tendon Organ (GTO) Desensitization Protocols',
      'The 7 Core Biomechanical Leaks in Human Locomotion'
    ],
    inGameMechanicMirror: 'In-game meter displays spring stiffness ratio; mistimed inputs trigger elastic leak penalty instead of stamina drain.',
    appliedScenarios: [
      {
        id: 'sc_1_1',
        scenario: 'The Ankle Collapse Under Penultimate Loading',
        context: 'An athlete approaches the rim with high velocity (7.2 m/s). Upon planting the right foot in the penultimate stride, the heel touches down heavily and the knee translates forward excessively beyond the toe.',
        prompt: 'According to the Neuro-Mechanic RNT framework, what is the primary underlying neuromuscular breakdown and the correct intervention?',
        options: [
          {
            id: 'opt_1',
            text: 'Weak quadriceps power — prescribe heavy barbell back squats.',
            rationale: 'Incorrect. Back squats build concentric strength but do not address reactive ankle stiffness or GTO reflex inhibition.',
            isCorrect: false
          },
          {
            id: 'opt_2',
            text: 'Deficient eccentric soleus/Achilles stiffness and premature dorsiflexion yield — implement RNT band-resisted pogo rebounds and ISO-extreme holds.',
            rationale: 'Correct! The kinetic energy was absorbed as heat rather than returned via Achilles tendon elastic recoil.',
            isCorrect: true
          },
          {
            id: 'opt_3',
            text: 'Excessive arm swing velocity — instruct the athlete to keep arms fixed during the plant.',
            rationale: 'Incorrect. Arm swing counter-movement actually contributes up to 15% of vertical impulse when timed with plant stiffness.',
            isCorrect: false
          }
        ]
      },
      {
        id: 'sc_1_2',
        scenario: 'Feeding the Asymmetry (RNT Methodology)',
        context: 'During an in-place jump landing, an athlete consistently shifts 68% of ground reaction force to their dominant left limb, demonstrating right hip abduction avoidance.',
        prompt: 'How would a Neuro-Mechanic facilitator utilize RNT to reflexively correct this pattern?',
        options: [
          {
            id: 'opt_a',
            text: 'Place an elastic band pulling the right hip further into adduction/internal rotation during landing drill.',
            rationale: 'Correct! By exaggerating the error (feeding the dysfunction), the nervous system reflexively fires the right glute medius and external rotators to restore balance.',
            isCorrect: true
          },
          {
            id: 'opt_b',
            text: 'Tell the athlete verbally to "think about putting more weight on the right side".',
            rationale: 'Incorrect. Conscious cortical overrides fail during high-velocity reflexive landings (< 200ms).',
            isCorrect: false
          },
          {
            id: 'opt_c',
            text: 'Immobilize the left leg with a brace so they are forced to use the right.',
            rationale: 'Dangerous and counter-productive for kinetic chain integration.',
            isCorrect: false
          }
        ]
      }
    ],
    creatorCardCredential: {
      id: 'cc_foundations_architect',
      cardName: 'Neuro-Mechanic Foundations Architect',
      rarity: 'Epic',
      badgeIcon: 'Zap',
      description: 'Awarded for master-level comprehension of RNT, SSC elasticity principles, and motor learning kinematics.'
    },
    facilitatorDiscussionPrompts: [
      'Have the participant explain why a trampoline jumper jump mechanics differ from a hardwood floor high-jumper.',
      'Demonstrate an active RNT band loop drill and observe the participant self-correcting their knee track without verbal cues.'
    ]
  },
  {
    id: 'module_02_strategy_cognition',
    number: 2,
    title: 'Strategy & Cognitive Load Under Fatigue',
    subtitle: 'Perception-Action Coupling & In-Game Decision Architecture',
    wordCountEstimate: '38,500 words (Curriculum Core)',
    coreConcepts: [
      'Cognitive tunneling: How elevated heart rate degrades peripheral field of view',
      'Affordance landscape: Reading defensive micro-cues before the kinematic initiation',
      'Gamified resilience: Converting mental hesitation into automated kinetic action',
      'Decision latency budgeting in high-speed sports scenarios'
    ],
    blueprintTopics: [
      'Visual Gaze Fixation vs Saccadic Sweeps',
      'Pre-Takeoff Auditory & Visual Cue Processing',
      'Neural Fatigability Indexes & PRQ Degradation Curves',
      'Game State Simulation in VR / Screen Mechanics'
    ],
    inGameMechanicMirror: 'The HUD dynamic timer shrinks in high-fatigue segments; successful pattern recognition restores bullet-time focus window.',
    appliedScenarios: [
      {
        id: 'sc_2_1',
        scenario: 'Late-Game Decision Latency & Vector Selection',
        context: 'With 12 seconds remaining in a tied match, heart rate at 188 bpm (94% HRmax), an athlete sees a closing defender closing out on their dominant right driving lane with high hands.',
        prompt: 'What cognitive-kinetic strategy preserves optimal kinetic transfer while avoiding collision turnover?',
        options: [
          {
            id: 'opt_2_1a',
            text: 'Force a straight-line deceleration into a 2-foot hop step, absorbing defender contact directly.',
            rationale: 'Sub-optimal. High fatigue reduces trunk stability, increasing risk of lumbar collapse on direct contact.',
            isCorrect: false
          },
          {
            id: 'opt_2_1b',
            text: 'Execute a pre-programmed Euro-step change of direction by transferring momentum through the stiff outer edge of the lateral foot.',
            rationale: 'Correct! Uses pre-established perceptual affordance to redirect linear momentum into an uncontested vector without braking.',
            isCorrect: true
          }
        ]
      }
    ],
    creatorCardCredential: {
      id: 'cc_cognitive_tactician',
      cardName: 'Cognitive Load Master Tactician',
      rarity: 'Rare',
      badgeIcon: 'Brain',
      description: 'Validated mastery in perception-action coupling, decision budgeting, and tactical composure under elevated heart rates.'
    },
    facilitatorDiscussionPrompts: [
      'Walk through a video clip of an athlete making a turnover: was it physical failure or cognitive latency?',
      'How does breathing cadence during stoppage time influence the subsequent 4-second decision window?'
    ]
  },
  {
    id: 'module_03_resilience_regulation',
    number: 3,
    title: 'Resilience & Autonomous Self-Regulation',
    subtitle: 'Connecting Physical Movement Screen Awareness to Emotional Autonomic Control',
    wordCountEstimate: '41,000 words (Curriculum Core)',
    coreConcepts: [
      'The Somatosensory Feedback Loop: Interoception as the foundation of mental grit',
      'Vagal nerve stimulation via diaphragmatic intra-abdominal pressure',
      'Reframing movement screen compensation patterns without shame or frustration',
      'De-escalation protocols for youth athletes under performance anxiety'
    ],
    blueprintTopics: [
      'Heart Rate Variability (HRV) as a Sovereign Metric',
      'Physiological Sigh & Pre-Competition Down-Regulation',
      'The Trauma-Informed Movement Screen Protocol',
      'Scope of Practice: Recognizing When to Refer to Licensed Mental Health Providers'
    ],
    inGameMechanicMirror: 'Visual noise in the viewport dims when player stabilizes their biometric breathing cadence to 4-7-8 rhythm.',
    appliedScenarios: [
      {
        id: 'sc_3_1',
        scenario: 'The Frustration Spiral After Failed Movement Gate',
        context: 'A 15-year-old participant fails the Level 2 Penultimate Stride GCT verification for the third consecutive week and throws their towel, claiming "my knees are just ruined forever."',
        prompt: 'As a certified Neuro-Mechanic facilitator, how do you apply Module 3 self-regulation protocol?',
        options: [
          {
            id: 'opt_3_1a',
            text: 'Remind them that failing builds character and force them to do 20 pushups immediately.',
            rationale: 'Counter-productive. Increases sympathetic overdrive and reinforces cortisol-driven shame.',
            isCorrect: false
          },
          {
            id: 'opt_3_1b',
            text: 'Execute a 90-second physiological sigh reset, re-frame the movement screen as an objective data mirror, and break down the metric into single-leg soleus activation micro-goals.',
            rationale: 'Correct! Decouples emotional identity from raw kinematic data and restores prefrontal cortex agency.',
            isCorrect: true
          }
        ]
      }
    ],
    creatorCardCredential: {
      id: 'cc_resilience_anchor',
      cardName: 'Autonomic Self-Regulation Anchor',
      rarity: 'Epic',
      badgeIcon: 'HeartPulse',
      description: 'Recognizes deep integration of autonomic regulation, HRV awareness, and psychological grounding under athletic duress.'
    },
    facilitatorDiscussionPrompts: [
      'How do you guide a participant through a poor movement screen score without diminishing their athletic identity?',
      'Review the referral protocol checklist for non-physical concerns.'
    ]
  },
  {
    id: 'module_04_goal_architecture',
    number: 4,
    title: 'Goal Architecture & Career Pipeline On-Ramp',
    subtitle: 'Deconstructing 10-Year Visions into Daily Executable Micro-Habits & Verifiable Portfolios',
    wordCountEstimate: '39,500 words (Curriculum Core)',
    coreConcepts: [
      'The Verifiable Portfolio vs the Self-Reported Resume',
      'The Sovereign Career Ladder: From Participant to Franchise Node Operator',
      'Institutional evidence synthesis for grant funding, collegiate scouts, and athletic directors',
      'Economic sovereignty through physical literacy and train-the-trainer certification'
    ],
    blueprintTopics: [
      'Creator Card Tokenized Credentialing',
      'Verifiable Movement Signature Cryptographic Signatures',
      'Facilitator-in-Training Apprenticeship Hours Log',
      'Grant Reporting Metrics: Measurable Kinematic & Educational Delta'
    ],
    inGameMechanicMirror: 'Completed milestones automatically mint on-chain verifiable credentials and unlock paid apprentice facilitator modules.',
    appliedScenarios: [
      {
        id: 'sc_4_1',
        scenario: 'Presenting to a High School Athletic Director or College Scout',
        context: 'A participant is preparing their senior year athletic portfolio to submit to collegiate programs and local community foundation grant boards.',
        prompt: 'What constitutes the most defensible, high-leverage submission package under the FEL University model?',
        options: [
          {
            id: 'opt_4_1a',
            text: 'A highlight mixtape video with heavy trap music and hype filters.',
            rationale: 'Standard social media content; provides zero verified kinematic data or measurable development history.',
            isCorrect: false
          },
          {
            id: 'opt_4_1b',
            text: 'A verified FEL Living Portfolio containing 12-month Movement Signature deltas, Level 1-3 competency sign-offs, Creator Card credentials, and Stress Test Analysis kinematic breakdown reels.',
            rationale: 'Correct! Provides verifiable, tamper-evident evidence of athletic durability, cognitive understanding, and work ethic.',
            isCorrect: true
          }
        ]
      }
    ],
    creatorCardCredential: {
      id: 'cc_sovereign_director',
      cardName: 'Sovereign Career Director',
      rarity: 'Sovereign Legendary',
      badgeIcon: 'Crown',
      description: 'Highest educational honors: Complete integration of all 4 Blueprint modules and full readiness for Facilitator Apprenticeship.'
    },
    facilitatorDiscussionPrompts: [
      'Help the student map their current PRQ progression into a 6-month goal architecture document.',
      'Review the student living portfolio for export readiness to athletic scouts or grant evaluators.'
    ]
  }
];

export const CAREER_LADDER_TIERS: CareerLadderStep[] = [
  {
    tier: 1,
    title: 'Tier 1: Active Participant',
    role: 'Movement Screen Baseline & Curriculum Student',
    compensationModel: 'Tuition-light / Free Tier Access + In-App Shard Economy',
    requirements: {
      physicalPrereq: 'Complete initial Neuro-Mechanic Mirror baseline scan',
      educationalPrereq: 'Enrollment in Blueprint Module 1 (Foundations)',
      facilitationHours: 0,
      validationCount: 1
    },
    unlocked: true,
    status: 'active',
    badge: 'Shield',
    deliverables: [
      'Movement Signature established with baseline PRQ',
      'Access to Level 1 Foundational Movement Series',
      'Daily AI Coach interactive check-ins'
    ]
  },
  {
    tier: 2,
    title: 'Tier 2: Certified Practitioner',
    role: 'Peer Mentor & Autonomous Physical Athlete',
    compensationModel: 'Earns Shard bounties for peer study sessions & Colosseum wins',
    requirements: {
      physicalPrereq: 'Level 1 & Level 2 Movement Progression fully verified',
      educationalPrereq: 'Completion of Blueprint Modules 1, 2, and 3 + Creator Cards',
      facilitationHours: 12,
      validationCount: 5
    },
    unlocked: true,
    status: 'active',
    badge: 'Award',
    deliverables: [
      'Verified Movement Signature with delta improvement',
      '3 Creator Card credentials in Living Portfolio',
      'Eligible for Facilitator-in-Training Apprenticeship'
    ]
  },
  {
    tier: 3,
    title: 'Tier 3: Facilitator-in-Training',
    role: 'Apprentice Facilitator under Senior Director Supervision',
    compensationModel: '$18–$24/hr stipend during supervised in-home delivery',
    requirements: {
      physicalPrereq: 'FMS1 Screening Administration Mastery (95%+ accuracy)',
      educationalPrereq: 'All 4 Blueprint Modules completed + Goal Architecture exam',
      facilitationHours: 40,
      validationCount: 15
    },
    unlocked: false,
    status: 'eligible',
    badge: 'GraduationCap',
    deliverables: [
      'Co-deliver 15 in-home diagnostic and progression sessions',
      'Complete youth mental health referral protocol training',
      'Demonstrate RNT band resistance setup live validation'
    ]
  },
  {
    tier: 4,
    title: 'Tier 4: Certified Facilitator',
    role: 'Autonomous In-Home Program Delivery & Screen Evaluator',
    compensationModel: '$45–$75/hr per in-home session (Self-Funding Protocol)',
    requirements: {
      physicalPrereq: 'Physical Tier 1 & 2 Facilitator Certification sign-off',
      educationalPrereq: 'Educational Tier 1 Facilitator Certification + CPR/First Aid',
      facilitationHours: 120,
      validationCount: 50
    },
    unlocked: false,
    status: 'locked',
    badge: 'CheckCircle2',
    deliverables: [
      'Manage cohort of 8–12 active participants in local zone',
      'Conduct monthly official Movement Re-screens',
      'Sign off on Level 1 & 2 competency progression gates'
    ]
  },
  {
    tier: 5,
    title: 'Tier 5: Regional Program Director',
    role: 'Cohort Manager & Facilitator Train-the-Trainer Lead',
    compensationModel: '$65,000–$95,000/yr salary / cohort revenue share',
    requirements: {
      physicalPrereq: '500+ verified screens administered with < 2% error rate',
      educationalPrereq: 'Master Facilitator Credential + Institutional Partner Liaison',
      facilitationHours: 500,
      validationCount: 200
    },
    unlocked: false,
    status: 'locked',
    badge: 'Building2',
    deliverables: [
      'Train and certify new Facilitator-in-Training cohorts',
      'Audit safety and clinical boundaries across regional hub',
      'Present outcome metrics to grant foundations and school districts'
    ]
  },
  {
    tier: 6,
    title: 'Tier 6: Franchise / Node Operator',
    role: 'Territory Owner & Sovereign Performance Lab Hub Leader',
    compensationModel: 'Lab Node Equity + Full Regional Revenue Ownership',
    requirements: {
      physicalPrereq: 'Fully validated institutional track record',
      educationalPrereq: 'Sovereign Node Governance Charter sign-off',
      facilitationHours: 1200,
      validationCount: 1000
    },
    unlocked: false,
    status: 'locked',
    badge: 'Crown',
    deliverables: [
      'Establish physical Sovereign Lab node with Unreal Pixel Streaming + Mirror',
      'Manage regional network of 15+ certified facilitators',
      'Contract with athletic leagues, community centers, and university partners'
    ]
  }
];

export const STRESS_TEST_CASES: StressTestCase[] = [
  {
    id: 'case_01_elite_dunk',
    title: 'Stress Test #01: Eastbay Rim Clearance (Penultimate SSC Analysis)',
    athlete: 'Elijah Bonds (Master Standard)',
    discipline: 'Basketball / High-Velocity Dunking',
    videoDuration: '0:14',
    sscEfficiency: 92.4,
    takeoffAngle: 78.5,
    groundContactTime: 164, // ms
    peakGRF: 4.8, // 4.8x bodyweight
    keyFrames: [
      {
        frameNumber: 1,
        timecode: '0:02.14',
        phase: 'Penultimate Heel-to-Toe Rocker Plant',
        biomechanicalFault: 'None — Optimal Achilles tendon pre-stretch',
        blueprintPrinciple: 'Module 1 Foundations: Elastic recoil maximization without knee valgus collapse.',
        jointAngles: { hip: 124, knee: 148, ankle: 74, trunk: 82 }
      },
      {
        frameNumber: 2,
        timecode: '0:03.02',
        phase: 'Block Foot Impact & Ground Reaction Force Peak',
        biomechanicalFault: 'Minor 3-degree right lateral trunk lean compensation',
        blueprintPrinciple: 'Module 1 & 2: Core intra-abdominal pressure prevents lumbar flexion energy leak.',
        jointAngles: { hip: 110, knee: 132, ankle: 88, trunk: 78 }
      },
      {
        frameNumber: 3,
        timecode: '0:04.18',
        phase: 'Triple Extension Launch & Flight Vector Apex',
        biomechanicalFault: 'None — 100% synchronized hip/knee/ankle extension',
        blueprintPrinciple: 'Level 3 Competency: Max vertical impulse conversion with 38.5 inch displacement.',
        jointAngles: { hip: 178, knee: 176, ankle: 142, trunk: 92 }
      }
    ]
  },
  {
    id: 'case_02_karate_kick',
    title: 'Stress Test #02: Mawashi Geri Kinetic Chain Transmission',
    athlete: 'Sovereign Martial Arts Cohort',
    discipline: 'Karate / Multi-Planar Rotational Power',
    videoDuration: '0:18',
    sscEfficiency: 88.1,
    takeoffAngle: 62.0,
    groundContactTime: 182,
    peakGRF: 3.9,
    keyFrames: [
      {
        frameNumber: 1,
        timecode: '0:03.45',
        phase: 'Plant Foot Pivot & Hip Internal Rotation',
        blueprintPrinciple: 'Module 1 RNT: Glute medius stabilization prevents pelvic tilt drop.',
        jointAngles: { hip: 135, knee: 155, ankle: 80, trunk: 88 }
      },
      {
        frameNumber: 2,
        timecode: '0:05.12',
        phase: 'Terminal Knee Extension & Kinetic Whip Apex',
        blueprintPrinciple: 'Module 2 Cognition: Rapid deceleration of opposing limb accelerates striking vector.',
        jointAngles: { hip: 168, knee: 178, ankle: 130, trunk: 74 }
      }
    ]
  }
];

export const INITIAL_SHARED_PROFILE: SharedProfileData = {
  athleteId: 'SOV-FEL-2026-0984',
  fullName: 'Elijah "Sovereign" Bonds',
  avatarSeed: 'Felix',
  joinedDate: 'October 2025',
  careerTier: 'Tier 2: Certified Practitioner',
  prqScore: 0.84,
  movementSignature: INITIAL_MOVEMENT_SIGNATURE,
  completedModuleIds: ['module_01_foundations', 'module_02_strategy_cognition'],
  earnedCreatorCards: [
    {
      id: 'cc_foundations_architect',
      cardName: 'Neuro-Mechanic Foundations Architect',
      moduleNumber: 1,
      rarity: 'Epic',
      issuedDate: '2026-01-15',
      credentialHash: '0x8f2a9c41b83d7e10',
      signatureAuthority: 'FEL-University-Protocol-v2'
    },
    {
      id: 'cc_cognitive_tactician',
      cardName: 'Cognitive Load Master Tactician',
      moduleNumber: 2,
      rarity: 'Rare',
      issuedDate: '2026-03-22',
      credentialHash: '0x4d1e78a99c0b3f52',
      signatureAuthority: 'FEL-University-Protocol-v2'
    }
  ],
  progressionLevels: PROGRESSION_SERIES,
  facilitatorCertifiedTiers: {
    physicalTier1: true,
    educationalTier1: true,
    leadTrainer: false
  },
  gamePerformanceHistory: [
    {
      gameMode: 'Dunk Contest Engine (UE5.7)',
      date: '2026-08-10',
      metric: 'Max Apex Vertical',
      score: '38.4 in / 164ms GCT',
      status: 'Verified'
    },
    {
      gameMode: 'Streetball Colosseum H2H',
      date: '2026-08-04',
      metric: 'Perception Latency Budget',
      score: '112ms / 94% Accuracy',
      status: 'Verified'
    },
    {
      gameMode: 'Brain Brawl Cognitive Sync',
      date: '2026-07-28',
      metric: 'Module 1-3 Integration Test',
      score: '100% / 10 Streaks',
      status: 'Verified'
    }
  ],
  portfolioVerificationCode: 'FEL-PORTFOLIO-VERIFIED-SHA256-b7f90c4412a8'
};
